version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: event-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@db:3306/event_db
    depends_on:
      - db
   

  frontend:
    build:
      context: ./frontend  
    container_name: event-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    # REMOVE volumes - include files in image

  db:
    image: docker.io/library/mysql:8.0
    container_name: event-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=event_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: